### ISSUE TITLE
Driver hot loading / pluggable architecture

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#68]
As we are moving away from relying on `go get` to fetch drivers, we need to re-implement a pluggable architecture to stay aligned with our vison. I will try to lay out some basic requirements and principals that we can use to measure and compare various candidate solutions.

 * Drivers should be dynamic, meaning
    * should not require daemon restart to load/reload/unload
    * should require minimal to none local config, use config repo as source of configuration
    * should accept new configs through hot or cold reload
    * should be acquired/upgraded/discarded dynamically without daemon restart
 * Drivers should be secured
    * sources should be validated using signature, certs etc
    * downloaded drivers should be validated using signature to prevent tampering

**Comment by wyardley** [comment]
I still argue that this [not having it hot-loadable] may be a feature and not a bug, especially in terms of containers, where we may want to consider them immutable. I would suggest maybe that we could also run into situations where we have a slow start because the container needs to re-download a big driver at start-time (or unpredictable behavior if a needed driver can't be obtained

I have some concerns security-wise as well about hot-loading / unloading drivers.

That said, if we add hot-plugging drivers, we should make sure that there's ironclad logging around when they're loaded and then unloaded, and that we log the version and checksum or result of GPG key check.

**Comment by Charles546** [comment]
Maybe we can use the kubernetes/docker model, where we use a registry to keep track of the drivers.  Organizations can maintain their own driver registries.  It can be as simple as a ftp, or http server or a bucket, where the binaries, signatures etc can be downloaded from. 

If the community is prosper enough, maybe someday there will be public registry that is trustworthy like the docker hub, or at least people can choose to trust some of the drivers in the public registry.

**Comment by wyardley** [comment]
I guess aside from the security issues, I'm not sure what problem we're trying to solve here.

I would actually see it as better in terms of predictability and stability to require either rebuilding (in the case of containers) or reloading the daemon (if running on bare metal / VM / compute instance) when new drivers are needed. Since Honeydipper is not a service that needs to be highly available (and a quick reload or redeploy should cause extremely little downtime), and (currently) is stateless, I don't really see why having hot loadable drivers is a good thing, other than to say that we have them.

**Comment by Charles546** [comment]
I think what I really want to achieve is zero-maintenance.  I have seen so many good softwares that are limited by their entry barrier and maintenance complexity.  Take spinnaker as an example, it is so complicated that it makes creating another software (halyard) to deploy and manage it sounds justifiable.  I guess I prefer to reduce the surface area of Honeydipper to the minimum, while still making it extensible and flexible through config files.  I agree that Injecting additional binaries into a running container is not ideal, but I would prefer to avoid having users rebuild or redeploy when extending Honeydipper, whenever it is possible.  Maybe we should tapping into some other things such as kubeless or cloudfunction etc.

**Comment by wyardley** [comment]
To me, with something like Spinnaker, it’s the complexity (which we’ve already got here as well), and the setup that’s hard more than the amount of maintenance involved.

This is literally a tool meant for people whose job it is to maintain software and infrastructure, so I guess I don’t see this as being a big issue, especially assuming the default drivers provide enough functionality for the typical user.
